// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loadgithub.proto

// 定义包名

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryFollowRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	FollowingEndCursor   string   `protobuf:"bytes,3,opt,name=followingEndCursor,proto3" json:"followingEndCursor,omitempty"`
	FollowerEndCursor    string   `protobuf:"bytes,4,opt,name=followerEndCursor,proto3" json:"followerEndCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryFollowRequest) Reset()         { *m = QueryFollowRequest{} }
func (m *QueryFollowRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFollowRequest) ProtoMessage()    {}
func (*QueryFollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{2}
}

func (m *QueryFollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryFollowRequest.Unmarshal(m, b)
}
func (m *QueryFollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryFollowRequest.Marshal(b, m, deterministic)
}
func (m *QueryFollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFollowRequest.Merge(m, src)
}
func (m *QueryFollowRequest) XXX_Size() int {
	return xxx_messageInfo_QueryFollowRequest.Size(m)
}
func (m *QueryFollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFollowRequest proto.InternalMessageInfo

func (m *QueryFollowRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *QueryFollowRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *QueryFollowRequest) GetFollowingEndCursor() string {
	if m != nil {
		return m.FollowingEndCursor
	}
	return ""
}

func (m *QueryFollowRequest) GetFollowerEndCursor() string {
	if m != nil {
		return m.FollowerEndCursor
	}
	return ""
}

type QueryFollowResp struct {
	Data                 *QueryFollowData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryFollowResp) Reset()         { *m = QueryFollowResp{} }
func (m *QueryFollowResp) String() string { return proto.CompactTextString(m) }
func (*QueryFollowResp) ProtoMessage()    {}
func (*QueryFollowResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{3}
}

func (m *QueryFollowResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryFollowResp.Unmarshal(m, b)
}
func (m *QueryFollowResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryFollowResp.Marshal(b, m, deterministic)
}
func (m *QueryFollowResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFollowResp.Merge(m, src)
}
func (m *QueryFollowResp) XXX_Size() int {
	return xxx_messageInfo_QueryFollowResp.Size(m)
}
func (m *QueryFollowResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFollowResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFollowResp proto.InternalMessageInfo

func (m *QueryFollowResp) GetData() *QueryFollowData {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryFollowData struct {
	Viewer               *Node       `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
	User                 *GithubUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryFollowData) Reset()         { *m = QueryFollowData{} }
func (m *QueryFollowData) String() string { return proto.CompactTextString(m) }
func (*QueryFollowData) ProtoMessage()    {}
func (*QueryFollowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{4}
}

func (m *QueryFollowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryFollowData.Unmarshal(m, b)
}
func (m *QueryFollowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryFollowData.Marshal(b, m, deterministic)
}
func (m *QueryFollowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFollowData.Merge(m, src)
}
func (m *QueryFollowData) XXX_Size() int {
	return xxx_messageInfo_QueryFollowData.Size(m)
}
func (m *QueryFollowData) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFollowData.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFollowData proto.InternalMessageInfo

func (m *QueryFollowData) GetViewer() *Node {
	if m != nil {
		return m.Viewer
	}
	return nil
}

func (m *QueryFollowData) GetUser() *GithubUser {
	if m != nil {
		return m.User
	}
	return nil
}

type Node struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	IsSiteAdmin          bool     `protobuf:"varint,2,opt,name=isSiteAdmin,proto3" json:"isSiteAdmin,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Company              string   `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Node) GetIsSiteAdmin() bool {
	if m != nil {
		return m.IsSiteAdmin
	}
	return false
}

func (m *Node) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Node) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type Follow struct {
	Nodes                []*Node   `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	PageInfo             *PageInfo `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Follow) Reset()         { *m = Follow{} }
func (m *Follow) String() string { return proto.CompactTextString(m) }
func (*Follow) ProtoMessage()    {}
func (*Follow) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{6}
}

func (m *Follow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Follow.Unmarshal(m, b)
}
func (m *Follow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Follow.Marshal(b, m, deterministic)
}
func (m *Follow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Follow.Merge(m, src)
}
func (m *Follow) XXX_Size() int {
	return xxx_messageInfo_Follow.Size(m)
}
func (m *Follow) XXX_DiscardUnknown() {
	xxx_messageInfo_Follow.DiscardUnknown(m)
}

var xxx_messageInfo_Follow proto.InternalMessageInfo

func (m *Follow) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Follow) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

type PageInfo struct {
	HasNextPage          bool     `protobuf:"varint,1,opt,name=hasNextPage,proto3" json:"hasNextPage,omitempty"`
	EndCursor            string   `protobuf:"bytes,2,opt,name=endCursor,proto3" json:"endCursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{7}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetHasNextPage() bool {
	if m != nil {
		return m.HasNextPage
	}
	return false
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

type GithubUser struct {
	Following            *Follow  `protobuf:"bytes,1,opt,name=following,proto3" json:"following,omitempty"`
	Followers            *Follow  `protobuf:"bytes,2,opt,name=followers,proto3" json:"followers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubUser) Reset()         { *m = GithubUser{} }
func (m *GithubUser) String() string { return proto.CompactTextString(m) }
func (*GithubUser) ProtoMessage()    {}
func (*GithubUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6256130ce94afd, []int{8}
}

func (m *GithubUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubUser.Unmarshal(m, b)
}
func (m *GithubUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubUser.Marshal(b, m, deterministic)
}
func (m *GithubUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubUser.Merge(m, src)
}
func (m *GithubUser) XXX_Size() int {
	return xxx_messageInfo_GithubUser.Size(m)
}
func (m *GithubUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubUser.DiscardUnknown(m)
}

var xxx_messageInfo_GithubUser proto.InternalMessageInfo

func (m *GithubUser) GetFollowing() *Follow {
	if m != nil {
		return m.Following
	}
	return nil
}

func (m *GithubUser) GetFollowers() *Follow {
	if m != nil {
		return m.Followers
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "service.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "service.HelloReply")
	proto.RegisterType((*QueryFollowRequest)(nil), "service.QueryFollowRequest")
	proto.RegisterType((*QueryFollowResp)(nil), "service.QueryFollowResp")
	proto.RegisterType((*QueryFollowData)(nil), "service.QueryFollowData")
	proto.RegisterType((*Node)(nil), "service.Node")
	proto.RegisterType((*Follow)(nil), "service.Follow")
	proto.RegisterType((*PageInfo)(nil), "service.PageInfo")
	proto.RegisterType((*GithubUser)(nil), "service.GithubUser")
}

func init() { proto.RegisterFile("loadgithub.proto", fileDescriptor_2e6256130ce94afd) }

var fileDescriptor_2e6256130ce94afd = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4b, 0x4f, 0x14, 0x41,
	0x10, 0xc7, 0x19, 0x99, 0x7d, 0xd5, 0x42, 0x90, 0x42, 0x93, 0x89, 0x7a, 0xd8, 0xb4, 0xf1, 0x71,
	0x80, 0x3d, 0xac, 0x17, 0x2f, 0xc6, 0x6c, 0x54, 0x50, 0x63, 0x08, 0x0e, 0xd1, 0x93, 0x97, 0x86,
	0x29, 0x86, 0xd6, 0xd9, 0xe9, 0xb1, 0xbb, 0x07, 0xdc, 0xab, 0x1f, 0xc4, 0xf8, 0x51, 0xcd, 0x74,
	0xf7, 0x3c, 0x90, 0xe5, 0xc0, 0x6d, 0xeb, 0xff, 0xff, 0x55, 0xa5, 0xeb, 0x31, 0x0b, 0x77, 0x33,
	0xc9, 0x93, 0x54, 0x98, 0xf3, 0xf2, 0x64, 0x5a, 0x28, 0x69, 0x24, 0x0e, 0x34, 0xa9, 0x0b, 0x71,
	0x4a, 0x8c, 0xc1, 0xc6, 0x7b, 0xca, 0x32, 0x19, 0xd3, 0xcf, 0x92, 0xb4, 0x41, 0x84, 0x30, 0xe7,
	0x0b, 0x8a, 0x82, 0x49, 0xf0, 0x7c, 0x14, 0xdb, 0xdf, 0xec, 0x29, 0x80, 0x67, 0x8a, 0x6c, 0x89,
	0x11, 0x0c, 0x16, 0xa4, 0x35, 0x4f, 0x6b, 0xa8, 0x0e, 0xd9, 0x9f, 0x00, 0xf0, 0x73, 0x49, 0x6a,
	0xb9, 0x2f, 0xb3, 0x4c, 0x5e, 0xd6, 0x25, 0xef, 0x41, 0x2f, 0x93, 0xa9, 0xc8, 0x3d, 0xee, 0x82,
	0x4a, 0x35, 0xf2, 0x07, 0xe5, 0xd1, 0x1d, 0xa7, 0xda, 0x00, 0xa7, 0x80, 0x67, 0x36, 0x59, 0xe4,
	0xe9, 0xbb, 0x3c, 0x79, 0x53, 0x2a, 0x2d, 0x55, 0xb4, 0x6e, 0x91, 0x15, 0x0e, 0xee, 0xc2, 0xb6,
	0x53, 0x49, 0xb5, 0x78, 0x68, 0xf1, 0xeb, 0x06, 0x7b, 0x0d, 0x5b, 0x57, 0xde, 0xa7, 0x0b, 0xdc,
	0x85, 0x30, 0xe1, 0x86, 0xdb, 0xb7, 0x8d, 0x67, 0xd1, 0xd4, 0xcf, 0x65, 0xda, 0xe1, 0xde, 0x72,
	0xc3, 0x63, 0x4b, 0x31, 0x7e, 0xa5, 0x40, 0x65, 0xe0, 0x13, 0xe8, 0x5f, 0x08, 0xba, 0x24, 0xe5,
	0x4b, 0x6c, 0x36, 0x25, 0x0e, 0x65, 0x42, 0xb1, 0x37, 0xf1, 0x19, 0x84, 0xa5, 0x26, 0x65, 0xbb,
	0x1d, 0xcf, 0x76, 0x1a, 0xe8, 0xc0, 0x6e, 0xe5, 0x8b, 0x26, 0x15, 0x5b, 0x80, 0xfd, 0x0d, 0x20,
	0xac, 0x32, 0x6f, 0x18, 0xdb, 0x04, 0xc6, 0x42, 0x1f, 0x0b, 0x43, 0xf3, 0x64, 0x21, 0xdc, 0xf0,
	0x86, 0x71, 0x57, 0xaa, 0xf2, 0x68, 0xc1, 0x45, 0xe6, 0xa7, 0xe6, 0x82, 0x66, 0xaf, 0x61, 0xbb,
	0x57, 0x7c, 0x04, 0xa3, 0xb2, 0x48, 0xb8, 0xa1, 0x64, 0x6e, 0xa2, 0x9e, 0x35, 0x5a, 0xa1, 0xda,
	0xf3, 0xa9, 0x5c, 0x14, 0x3c, 0x5f, 0x46, 0x7d, 0xb7, 0x67, 0x1f, 0xb2, 0x6f, 0xd0, 0x77, 0x03,
	0xc0, 0xc7, 0xd0, 0xcb, 0x65, 0x42, 0x3a, 0x0a, 0x26, 0xeb, 0xd7, 0x7b, 0x77, 0x1e, 0xee, 0xc1,
	0xb0, 0xe0, 0x29, 0x7d, 0xc8, 0xcf, 0xa4, 0x6f, 0x7f, 0xbb, 0xe1, 0x8e, 0xbc, 0x11, 0x37, 0x08,
	0xfb, 0x08, 0xc3, 0x5a, 0xad, 0xba, 0x3d, 0xe7, 0xfa, 0x90, 0x7e, 0x99, 0xa3, 0xfa, 0xde, 0x86,
	0x71, 0x57, 0xaa, 0x7a, 0xa0, 0x66, 0xf1, 0xee, 0x94, 0x5a, 0x81, 0x7d, 0x07, 0x68, 0x07, 0x8c,
	0x7b, 0x30, 0x6a, 0x4e, 0xc8, 0x6f, 0x6b, 0xab, 0x79, 0x89, 0xbf, 0x89, 0x96, 0x68, 0x71, 0x52,
	0xda, 0x3f, 0xfc, 0x26, 0x9c, 0x94, 0x9e, 0xfd, 0x0e, 0x60, 0x70, 0xa0, 0x88, 0x0c, 0x29, 0x7c,
	0x09, 0xc3, 0x63, 0xbe, 0xb4, 0x1f, 0x0d, 0xde, 0x6f, 0x72, 0xba, 0x1f, 0xda, 0x83, 0x9d, 0xff,
	0xe5, 0x22, 0x5b, 0xb2, 0x35, 0x7c, 0x05, 0x9b, 0x75, 0xe6, 0x3c, 0xe5, 0x22, 0xbf, 0x5d, 0xfa,
	0xec, 0x2b, 0x6c, 0xb8, 0x86, 0x3f, 0x49, 0x9e, 0x90, 0xc2, 0x7d, 0x18, 0x77, 0x0e, 0x16, 0x1f,
	0xae, 0xba, 0xef, 0xba, 0x64, 0xb4, 0xda, 0xd4, 0x05, 0x5b, 0x3b, 0xe9, 0xdb, 0xbf, 0x8d, 0x17,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0xcd, 0xce, 0xa9, 0x4a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/service.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/service.Greeter/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Greeter/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Greeter_SayHelloAgain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadgithub.proto",
}

// GithubLoaderClient is the client API for GithubLoader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GithubLoaderClient interface {
	QueryFollow(ctx context.Context, in *QueryFollowRequest, opts ...grpc.CallOption) (*QueryFollowResp, error)
}

type githubLoaderClient struct {
	cc *grpc.ClientConn
}

func NewGithubLoaderClient(cc *grpc.ClientConn) GithubLoaderClient {
	return &githubLoaderClient{cc}
}

func (c *githubLoaderClient) QueryFollow(ctx context.Context, in *QueryFollowRequest, opts ...grpc.CallOption) (*QueryFollowResp, error) {
	out := new(QueryFollowResp)
	err := c.cc.Invoke(ctx, "/service.GithubLoader/QueryFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubLoaderServer is the server API for GithubLoader service.
type GithubLoaderServer interface {
	QueryFollow(context.Context, *QueryFollowRequest) (*QueryFollowResp, error)
}

func RegisterGithubLoaderServer(s *grpc.Server, srv GithubLoaderServer) {
	s.RegisterService(&_GithubLoader_serviceDesc, srv)
}

func _GithubLoader_QueryFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubLoaderServer).QueryFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.GithubLoader/QueryFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubLoaderServer).QueryFollow(ctx, req.(*QueryFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GithubLoader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.GithubLoader",
	HandlerType: (*GithubLoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryFollow",
			Handler:    _GithubLoader_QueryFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadgithub.proto",
}
